# Function to generate cross HR comparison table
# using the log odds ratios generated by BUGS
# Howard Thom 24-July-2018

summary.stats<-function(x,n.digits=2,med=FALSE)
{
	if(med){
		return(paste0(round(median(x),digits=n.digits)," (",round(quantile(x,probs=c(0.025)),digits=n.digits),", ",round(quantile(x,probs=c(0.975)),digits=n.digits),")"))
	}else{
		return(paste0(round(mean(x),digits=n.digits)," (",round(quantile(x,probs=c(0.025)),digits=n.digits),", ",round(quantile(x,probs=c(0.975)),digits=n.digits),")"))
	}
}

cross.or<-function(bugs.object,t.names,med=FALSE)
{
	or.table<-matrix(NA,nrow=length(t.names),ncol=length(t.names))
	rownames(or.table)<-colnames(or.table)<-t.names
	for(i in 2:length(t.names))
	{
		# Comparisons with reference
		or.table[i,1]<-summary.stats(exp(bugs.object$sims.array[,,grep("d",rownames(bugs.object$summary))[i-1]]),med=med)
		or.table[1,i]<-summary.stats(exp(-bugs.object$sims.array[,,grep("d",rownames(bugs.object$summary))[i-1]]),med=med)
		for(j in 2:length(t.names))
		{
			or.table[i,j]<-summary.stats(exp(
				bugs.object$sims.array[,,grep("d",rownames(bugs.object$summary))[i-1]]-
					bugs.object$sims.array[,,grep("d",rownames(bugs.object$summary))[j-1]]
			),med=med)			
		}
	}
	for(i in 1:length(t.names))or.table[i,i]<-t.names[i]

	# Sort the table alphabetically for ease of comparison with earlier results
	#or.table<-or.table[sort(t.names),sort(t.names)]
	return(or.table)
}